package com.lostfound.servlet;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Date;
import java.util.List;

import com.lostfound.dao.ItemDAO;
import com.lostfound.model.Item;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class ReportDownloadServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        if (request.getSession().getAttribute("adminUsername") == null) {
            response.sendRedirect(request.getContextPath() + "/adminLogin");
            return;
        }

        String fromParam = request.getParameter("from");
        String toParam   = request.getParameter("to");

        if (fromParam == null || fromParam.isEmpty() || toParam == null || toParam.isEmpty()) {
            response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Please provide both 'from' and 'to' date parameters.");
            return;
        }

        Date fromDate;
        Date toDate;
        try {
            fromDate = Date.valueOf(fromParam); 
            toDate   = Date.valueOf(toParam);
        } catch (IllegalArgumentException e) {
            response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Invalid date format. Use yyyy-MM-dd.");
            return;
        }

        ItemDAO itemDAO = new ItemDAO();
        List<Item> items = itemDAO.getItemsByDateRange(fromDate, toDate);

       
        long lostCount     = items.stream().filter(i -> "lost".equalsIgnoreCase(i.getType())).count();
        long foundCount    = items.stream().filter(i -> "found".equalsIgnoreCase(i.getType())).count();
        long openCount     = items.stream().filter(i -> "open".equalsIgnoreCase(i.getStatus())).count();
        long resolvedCount = items.stream().filter(i -> "resolved".equalsIgnoreCase(i.getStatus())).count();

       
        String filename = "LostFound_Report_" + fromParam + "_to_" + toParam + ".csv";

        response.setContentType("text/csv; charset=UTF-8");
        response.setHeader("Content-Disposition", "attachment; filename=\"" + filename + "\"");

        PrintWriter writer = response.getWriter();

        
        writer.println("Lost & Found Report");
        writer.println("Generated by,Admin: " + request.getSession().getAttribute("adminUsername"));
        writer.println("Date Range,From: " + fromParam + ",To: " + toParam);
        writer.println("Total Items in Range," + items.size());
        writer.println("Lost Items," + lostCount);
        writer.println("Found Items," + foundCount);
        writer.println("Open Items," + openCount);
        writer.println("Resolved Items," + resolvedCount);
        writer.println(); 

        
        writer.println("Item ID,Type,Title,Category,Location,Status,Date Reported,Reported By,Reporter Email,Reporter Phone");

        
        for (Item item : items) {
            writer.printf("%d,%s,\"%s\",%s,\"%s\",%s,%s,\"%s\",%s,%s%n",
                item.getItemId(),
                item.getType(),
                item.getTitle() != null ? item.getTitle().replace("\"", "\"\"") : "",
                item.getCategory() != null ? item.getCategory() : "",
                item.getLocation() != null ? item.getLocation().replace("\"", "\"\"") : "",
                item.getStatus() != null ? item.getStatus() : "",
                item.getDateReported() != null ? item.getDateReported().toString() : "",
                item.getReporterName() != null ? item.getReporterName().replace("\"", "\"\"") : "",
                item.getReporterEmail() != null ? item.getReporterEmail() : "",
                item.getReporterPhone() != null ? item.getReporterPhone() : ""
            );
        }

        writer.flush();
    }
}
